app/components/tests/InviteCandidatePopup.tsx

Fixed the following issue:
- Input field state not resetting after closing inviteCandidatePopup

bug-fix-inviteMembers

---

app/components/tests/AddTest.tsx
app/components/tests/StepsTab.tsx
app/components/tests/TestList.tsx
app/routes/sections.tsx
cypress/e2e/tests/add-test.cy.ts

Fixed the following issue:
- In Add Test, Step 2 and Step 3 were accessible while the name and description fields were empty, those clickable steps were creating UI flickering

bug-fix-addTest

---

app/components/sections/Sections.tsx
tailwind.config.js

fixed section right side card at 1024 viewport

fix(): fixed section right side card at 1024 viewport

---

app/components/assessment/Timer.tsx
app/components/members/AddMemberModal.tsx
app/components/sections/AddSection.tsx
app/components/tests/CreateTestPreview.tsx
app/constants/common.constants.ts
cypress/e2e/section-tests/Section.cy.ts

Add Section :
- Add section modal is closing unexpectedly, if we click on add button without entering any value
- Add section & Add member form is not resetting

134 on adding section if description is empty and clicked on add popup is closing with toast this is not expected behaviour

---

app/components/DeletePopUp.tsx
app/components/members/MemberListItem.tsx
app/components/sections/SectionCard.tsx
app/components/tests/TestTableItem.tsx
app/constants/common.constants.ts

proper delete message has been added for section test and member

fix(): proper delete message has been added for the specific use case

---

app/components/form/Dropdown.tsx
app/components/sections/add-question/QuestionEditor.tsx

Fixed the following issues,
- Quill editor was seen through the Dropdown component
- Added wrapper around dropdown component for fixed width

Dropdown Component

---

app/components/DeletePopUp.tsx
app/models/sendgrid.servers.ts
public/locales/en/index.json

Email template is distorted in dark mode :- Fixed

email layout fixed

---

app/components/results/GroupByTestItems.tsx
app/components/tests/TestTableItem.tsx

removed truncate from test name in results and test page

fix(): fixed test name truncate part in results and test page

---

app/components/barGraph/barGraph.tsx
app/components/members/MemberListItem.tsx
app/components/sections/SectionCard.tsx
app/components/sections/Sections.tsx
app/routes/sections.tsx

APIs getting cancelled on section change: fixed
Warning on console on section page: fixed

fix: section api failing issue

---

app/components/assessment/Question.tsx
app/styles/global.css

- Disable copy of questions from assessment page.
- Disable paste in textarea for answers.

HOT FIX: disable copy and paste in assessment

---

app/components/results/AttendedCandidateListItem.tsx
cypress/e2e/add-questions/AddQuestion.cy.ts

Fixes invalid date in candidate result table

---

app/components/settings/GeneralSettings.tsx

Gap between label and value should be reduced in settings #306

---

app/components/results/GroupByTests.tsx

- change default value in state.

Latest results should be shown on top on Results Page #354

---

app/components/settings/ResetPassword.tsx

-  **Removed :** Password validation for new password and confirm password after submitting
-  **Added :** Password validation for new password and confirm password , when user starts entering the password is **added**

307 error showing is abrupt

---

app/components/Dialog.tsx
app/components/members/InvitedMembersList.tsx
app/components/members/MembersHeader.tsx
app/components/sections/QuestionCard.tsx
app/components/sections/SectionCard.tsx
app/routes/members.tsx
app/routes/tests.tsx
cypress/e2e/group-by-test/groupByTestTable.cy.ts
cypress/e2e/members-test/members.cy.ts
cypress/e2e/section-tests/Section.cy.ts

added test cases for
groupByTestTable.cy.ts
Members.cy.ts
Section.cy.ts

323 add test cases for ctas and title texts

---

app/components/SideNavFooter.tsx
app/components/login/SignUp.tsx
app/components/side-nav/SideNav.tsx
app/components/tests/AddTest.tsx
cypress/e2e/side-nav-tests/SideNavTests.cy.ts
cypress/e2e/sign-up/SignUp.cy.ts
cypress/e2e/tests/add-test.cy.ts

Ran updated test with CLI, here is result:

324 add test cases for ctas and title texts

---

app/components/settings/ResetPassword.tsx

- Password validations improved

371- Settings->Change password issue

---

app/components/login/SignUp.tsx

- reset error for email field when it is cleared

388 - SignupPage: reset error if user clear the input field 

---

app/components/SideNavHeader.tsx

sidenav heading is clickable along with logo

sidenav-heading-clickable

---

app/components/sections/add-question/OptionForQuestion.tsx

on add question text type questions, restriction added not taking blank input filed at the beginning

add-question-type-text-restrict-blank-options

---

app/components/side-nav/SideNav.tsx
app/components/tests/CreateTestPreview.tsx
public/locales/en/index.json

- Add unit for test time in test preview.

416 in assessment while creating assessment in preview tab unit can be added in front of the total time

---

app/components/tests/SelectSectionCard.tsx

- Check for test time cannot be blank or 0 is added

420 - In assessments, While creating assessment, test time can be entered as 0 or can be kept empty. Check should be added here for minimum time 1min.

---

app/components/tests/InviteCandidatePopup.tsx
tailwind.config.js

max height given to invite candidate pop up and added scroll

invite-candidate-popup-give-max-height-to-popup-and-add-scroll

---

app/components/sections/SectionDetails.tsx

- If there are no questions in section, then search bar is disabled.

417 - In Tests, if test do not have any questions then search-bar should be disabled.

---

app/components/login/Login.tsx

- update error handling on login page

393 - Login Page: reset error if user clear the input field 

---

app/routes/sign-in.tsx
public/locales/en/index.json

- Update error text for user authentication to "Incorrect email or password".

421 - On login, show common error "Incorrect email or passsword"

---

app/components/login/UserForgetPassword.tsx
app/models/user.server.ts
app/routes/forgot-password.tsx

- Update error handling for forgot password input field. Error message will be removed user clears the input field.

387 - Forgot password, reset error if user clear the text box

---

app/models/candidate.server.ts

after sending the link to the candidate link sent  date time will  update

after-resending-invite-linkDate-updated

---

app/components/results/CandidateListOfTest.tsx
app/models/result.server.ts

- Latest result in candidate list in results will be on top

399 - Candidate List in results should show latest on top 

---

app/components/results/CandidateListOfTest.tsx
app/routes/$workspaceId.tsx

if current workspace not exist then user will be redirect to the default workspace

workspace-scenario-handles

---

app/components/results/CandidatesList.tsx

414 - Add no data text

---

app/components/sections/add-question/OptionForQuestion.tsx
app/root.tsx
app/styles/global.css
app/styles/quill.css
app/styles/toastify.css

- Auto resize quill for options

 394 - auto resize the quill editor for option

---

app/components/sections/AddEditSection.tsx
app/components/sections/SectionCard.tsx
app/components/sections/Sections.tsx
app/interface/Interface.tsx
app/routes/$workspaceId/tests.tsx

- Error text will be shown under inputs while editing section.

395 - At the time of the edit section…error not showing below input field. Toaster is showing

---

app/models/invites.server.ts
app/routes/workspace.$inviteId.join.tsx

- After accepting invite, user will now navigate to joined workspace.

376 - after accepting workspace invite, user should redirect to same workspace he has joined

---

app/components/QuillEditor.client.tsx
app/styles/quill.css

- quill editor for question, UI is fixed

452- fix quill editor(Question) css

---

app/components/login/SignUp.tsx
app/routes/sign-up.tsx

- Email field in sign up form will preloaded when not registered user clicks on invite link.

466 - Preload email when click on invite link on signup and disable the field

---

app/models/result.server.ts

- Sort by descending, in single assessment in results page ,

488 - HOTFIX: Result candidate list sorted by latest invite date

---

app/models/invites.server.ts
cypress/e2e/forgot-password/ForgotPassword.cy.ts
cypress/e2e/section-tests/Section.cy.ts
cypress/e2e/settings-tests/Settings.cy.ts
cypress/e2e/smoke.cy.ts

- Fix failing test cases
- Update get condition for invited members list

Test case fix 2

---

app/components/login/SignUp.tsx

- Handle reset error if user clears input field on signup page

388 signuppage reset error if user clear the input field 

---

app/components/login/Login.tsx
app/components/workspace/JoinWorkspace.tsx
app/routes/logout.tsx
app/routes/sign-in.tsx
app/routes/workspace.$inviteId.join.tsx
app/session.server.ts
public/locales/en/index.json

Switch account: logout the user
Goto Homepage: ignore invite and continue using the app

if-invalid-account-is-loggedin-when-clicking-on-join-link-give-cta

---

app/components/common-components/Badge.tsx
app/components/members/MembersList.tsx
app/interface/Interface.tsx
app/models/workspace.server.ts
app/routes/$workspaceId/members.tsx
cypress/e2e/members-test/members.cy.ts
public/locales/en/index.json

- Owner tag will be shown next to workspace owner

Add owner tag (on Updated Members Table)

---

app/components/tests/AddTest.tsx
app/components/tests/SelectSectionCard.tsx
package-lock.json

disabled next button when time is 0 or empty

Assessment: Add Assessment -> on adding section, time check issue.#516

---

app/components/common-components/PasswordInputField.tsx
app/components/login/SignUp.tsx
app/components/settings/ResetPassword.tsx
app/interface/Interface.tsx
app/routes/sign-up.tsx
package-lock.json

added scrolling in sign up page

fix:Sign-up page should be scrollable

---

app/components/assessment/CandidateInstruction.tsx

Update instructions and refactor code

Remove second and last instructions, and add -once submitted cannot be changed 

---

app/components/form/CheckBox.tsx
app/components/login/Login.tsx
app/components/login/SignUp.tsx
app/session.server.ts
public/locales/en/index.json

Remember me functionality in sign-in page

Remember me functionality #524

---

app/components/TestListActionMenu.tsx
app/components/common-components/DeletePopUp.tsx
app/components/tests/TestList.tsx
cypress/e2e/smoke.cy.ts
cypress/e2e/tests/test-table.cy.ts

case-fixed: whenever user tries to open popup on assessment table there are multiple popups are open in DOM...

fix(): multi-popup_issue

---

app/components/members/MembersWrapper.tsx
cypress/e2e/settings-tests/Settings.cy.ts

after double clicking on members side nav link, params are not showing in url

fix(): members page params redirection

---

cypress.config.ts
cypress/e2e/members-test/members.cy.ts

test case for reinvite member
note: some test cases are already done for this, i just add the possible one which missed

543 test case for resend invite

---

app/components/sections/add-question/OptionForQuestion.tsx

if multiple choice is selected then after 2 options delete button is visible and if text type then after 1

On add question, if options length is 2 or less, don't show delete icon

---

app/components/common-components/PasswordInputField.tsx

password field is overlapping icon

574 password field is overlapping icon

---

app/routes/$workspaceId/tests.tsx

test-page-list-re-render-as-soon-as-we-visit-the-page-sorting…change-occur

test-page-list-re-render-as-soon-as-we-visit-the-page-sorting…change-occur

---

.github/workflows/deploy.yml
app/components/SideNavFooter.tsx
app/components/assessment/CandidateOtpVerification.tsx
app/components/common-components/Button.tsx
app/interface/Interface.tsx
cypress/e2e/side-nav-tests/SideNavTests.cy.ts
package-lock.json
package.json

Updated Prisma Version to 4.9.0

634 update prisma version

---

app/components/services/results.service.ts
app/routes/$workspaceId/results/groupByTests/$testId.$candidateId.tsx
app/routes/$workspaceId/results/groupByTests/$testId.tsx
app/routes/$workspaceId/results/groupByTests/index.tsx
app/routes/$workspaceId/results/index.tsx
app/services/results.service.ts

refactor: result route

---

app/routes/$workspaceId/tests.tsx
app/services/tests.service.ts

Refactor services imports

---

app/components/sections/add-question/AddQuestionInSection.tsx
app/components/sections/add-question/OptionForQuestion.tsx
app/models/sections.server.ts
package-lock.json
package.json
prisma/schema.prisma

Updated CUID to UUID, added a package:
- uuid
- @types/uuid
We have manually created CUID, updated them also to UUID

refactor(): updated CUID to UUID

---

app/routes/$workspaceId/tests/$sectionId.tsx
app/services/tests.service.ts

Deleting question is working but giving error on staging

Deleting question is working but giving error on staging

---

app/components/tests/AddTest.tsx
app/components/tests/CreateTestPreview.tsx
app/components/tests/TestDetails.tsx

When we are on test Preview we don't need sorting, so we don't need  that prop so  I have make it as optional

fix: removed onSelectedSectioncChange prop from test details

---

app/routes/$workspaceId/tests.tsx

Updated Dependency for Order change

720 test page ascending descending sort not working

---

app/routes/$workspaceId/tests.tsx

Added useEffect to store the order and sortBy values in global context

721 tests on adding question sorting of tests is changing

---

app/components/workspace/JoinWorkspace.tsx
app/routes/$.tsx
app/routes/$workspaceId/$.tsx
public/locales/en/index.json

755 update en indexjson rename 404 key to notfound

---

app/components/common-components/EmptyStateComponent.tsx
app/components/results/GroupByTests.tsx
app/components/sections/SectionDetails.tsx
app/components/tests/TestList.tsx
app/routes/$workspaceId/tests.tsx
public/locales/en/index.json

Updated empty states of tests, results, assessment and no question states

756 tets details when there is no data in the sectionno questions update the text message

---

app/components/results/ResultDetailsQuestionsPreview.tsx
public/locales/en/index.json

toggle key given answers and correct answers according to question

---

public/locales/en/index.json

744 expired link constant is missing on candidate side
